server:
  port: ${SERVER_PORT:8099}
spring:
  main:
    banner-mode: "off"
  # Datasource
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/tutor}
    driverClassName: org.postgresql.Driver
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:password}
  flyway:
    enabled: true
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:false}
  # Jackson config
  jackson:
    serialization:
      write-dates-as-timestamps: true
      write-date-timestamps-as-nanoseconds: false
    default-property-inclusion: non_null
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
# Logging
logging:
  level:
    ru.maxvgrad.tutor: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.security: DEBUG

springfox:
  documentation:
    auto-startup: ${SPRING_FOX_AUTO_STARTUP:TRUE}